.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TOPIC" "" "May 2013" "" "Git addons"
.
.SH "NAME"
\fBtopic\fR \- handle topic branches with ease\.
.
.SH "SYNOPSIS"
\fBgit topic <option> command\fR
.
.SH "DESCRIPTION"
An opinionated tool for topic branches\.
.
.SH "COMMANDS"
.
.TP
\fBgit topic\fR
Show the current topic
.
.TP
\fBgit topic list\fR
Show all topic branches
.
.TP
\fBgit topic switch <name>\fR, \fBgit topic <name>\fR
Switch to the specified topic
.
.TP
\fBgit topic merge <target>\fR
Merge the current topic branch into \fBtarget\fR\. The \fBtarget\fR name is optional and defaults to \fBmaster\fR\.
.
.TP
\fBgit topic finish <target>\fR
Like merge, but stays in the target branch\.
.
.TP
\fBgit topic clean\fR
Delete all merged topic branches\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-short\fR
Show only the short description when running \fBgit topic\fR
.
.SH "BUGS"
None known yet\.
.
.SH "AUTHOR"
@radiospiel (http://github\.com/radiospiel)
.
.SH "COPYRIGHT"
The git\-topic tool is copyrighted under the terms of the Simplified BSD License\. Check the file COPYING\.BSD for details\.
.
.SH "INSTALLATION"
Install git\-topic via \fBmake install\fR\. Make sure /usr/local/bin is in your \fB$PATH\fR, and /usr/local/share/man is in your \fB$MANPATH\fR\.
.
.SH "CONTRIBUTIONS"
Fork me on github: https://github\.com/radiospiel/git\-topic
